### PR TITLE
Url work mb

### PR DESCRIPTION
**Pull request by ADLMeganBohland**
Work done on enabled Moodle to communicate with CMI5 player. CMI5 player now generates and sends re ID. Moodle uses this instead of randomly creating it's own.

### CODE REVIEW

**Comment by rajkowski** [comment]
Thanks @ADLMeganBohland  I'm starting to review the changes.

Can you combine the hardcoded http, the cmi5launchplayerurl value, and the cmi5launchplayerport value?

When the Admin configures the 'cmi5 player url', it should be a single setting containing the URL scheme, name, and optional port. So one setting which an admin will populate with a full and valid URL: "https://mycmi5player.example.com"

In the code there is an assumption that http will be used (it could be a remote service requiring https) and it's possible that a port would not be specified:

 //Build URL to import course to
         $url= "http://" . $settings['cmi5launchplayerurl'] . ":" . $settings['cmi5launchplayerport'] . "/api/v1/course" ;

**Comment by ADLMeganBohland** [comment]
Hey Matt,

I think I can make these changes. When the plugin is installed it asks for the addy/port separate. You want me to change this correct? So the admin only enters one thing?
***@***.***

Thank you!

Megan Bohland
Software Engineer II
SimIS
Advanced Distributed Learning (ADL) Initiative

**Comment by rajkowski** [comment]
Yes, exactly that! "So the admin only enters one thing"

**Comment by rajkowski** [comment]
Hi @ADLMeganBohland, I noticed another instance of the Moodle URL itself is being referenced. There might be a global function (I looked but didn't find one, so I have a recommendation...

Replace:

```
 //We need to parse and cutoff from the ///
     //Build url to pass as returnUrl
 	$returnUrl = ('http://' . $_SERVER['HTTP_HOST'] . $_SERVER['PHP_SELF'] .'/mod/cmi5launch/view.php'. '?id=' .$cm->id);
```

with:

```
$returnUrl = $CFG->wwwroot . $_SERVER['SCRIPT_NAME'] . '/mod/cmi5launch/view.php'. '?id=' .$cm->id;
```

Use CFG->wwwroot to get the Admin's intended Moodle URL, with scheme (the url could be behind a proxy, use SSL, etc.), and use  SCRIPT_NAME to prevent spoofing

**Comment by ADLMeganBohland** [comment]
@rajkowski , By doing this: 
$returnUrl = $CFG->wwwroot .'/mod/cmi5launch/view.php'. '?id=' .$cm->id;
We are able to build the return URL correctly. This should prevent issues with proxy servers, but have not found a way to also use 'SCRIPT_NAME'.

**Review by rajkowski — APPROVED** [review]
The contribution looks great! Thanks Megan

**Comment by servosdesign** [comment]
I keep getting this error when trying to launch cmi5 courses in Moodle. I know everything works because I've tested it using the [CATAPULT cts](https://github.com/adlnet/CATAPULT) and am able to launch courses. For some reason I can't get these courses to launch on moodle though.

```
The Learning Record Store is not available. Please contact a system administrator. If you are the system administrator, go to Site admin / Development / Debugging and set Debug messages to DEVELOPER. Set it back to NONE or MINIMAL once the error details have been recorded.
Error attempting to get registration data from State API.

object(cmi5\LRSResponse)#1811 (3) {
  ["success"]=>
  bool(false)
  ["content"]=>
  string(203) "{"message":"Query does not match schema: querystring.activityId does not conform to the \"uri\" format","err":"Query does not match schema: querystring.activityId does not conform to the \"uri\" format"}"
  ["httpResponse"]=>
  array(4) {
    ["status"]=>
    int(400)
    ["headers"]=>
    array(5) {
      ["contentType"]=>
      string(16) "application/json"
      ["date"]=>
      string(29) "Thu, 25 May 2023 19:08:41 GMT"
      ["etag"]=>
      string(34) "W/"cb-U0yOvLzsMHCnrpAzEQZy9zbPZK8""
      ["apiVersion"]=>
      string(5) "1.0.3"
      ["contentTypeCharset"]=>
      string(5) "utf-8"
    }
    ["_content"]=>
    string(203) "{"message":"Query does not match schema: querystring.activityId does not conform to the \"uri\" format","err":"Query does not match schema: querystring.activityId does not conform to the \"uri\" format"}"
    ["_metadata"]=>
    array(11) {
      ["crypto"]=>
      array(4) {
        ["protocol"]=>
        string(7) "TLSv1.3"
        ["cipher_name"]=>
        string(22) "TLS_AES_256_GCM_SHA384"
        ["cipher_bits"]=>
        int(256)
        ["cipher_version"]=>
        string(7) "TLSv1.3"
      }
      ["timed_out"]=>
      bool(false)
      ["blocked"]=>
      bool(true)
      ["eof"]=>
      bool(false)
      ["wrapper_data"]=>
      array(20) {
        [0]=>
        string(24) "HTTP/1.1 400 Bad Request"
        [1]=>
        string(35) "Date: Thu, 25 May 2023 19:08:41 GMT"
        [2]=>
        string(45) "Content-Type: application/json; charset=utf-8"
        [3]=>
        string(19) "Content-Length: 203"
        [4]=>
        string(17) "Connection: close"
        [5]=>
        string(21) "X-Powered-By: Express"
        [6]=>
        string(25) "X-Rate-Limit-Limit: 10000"
        [7]=>
        string(28) "X-Rate-Limit-Remaining: 9779"
        [8]=>
        string(28) "X-Rate-Limit-Reset: 74057459"
        [9]=>
        string(12) "Vary: Origin"
        [10]=>
        string(38) "Access-Control-Allow-Credentials: true"
        [11]=>
        string(157) "Access-Control-Expose-Headers: etag,X-Experience-API-Consistent-Through,X-Experience-API-Version,X-Rate-Limit-Limit,X-Rate-Limit-Remaining,X-Rate-Limit-Reset"
        [12]=>
        string(31) "X-Experience-API-Version: 1.0.3"
        [13]=>
        string(40) "ETag: W/"cb-U0yOvLzsMHCnrpAzEQZy9zbPZK8""
        [14]=>
        string(24) "CF-Cache-Status: DYNAMIC"
        [15]=>
        string(256) "Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=UwKZq9lR%2FutrobVOECO7MN4U58SfDXWYhRAUf4B8YLVkDus3O3wSOIlcTlRj%2BhJXcgpZfHJeH2rRyp1xDc4JqiA3bbtnTQeFtHchlWwgZa29mji84BycVgGqL7ccI52G7QlQ2bo4"}],"group":"cf-nel","max_age":604800}"
        [16]=>
        string(65) "NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}"
        [17]=>
        string(18) "Server: cloudflare"
        [18]=>
        string(28) "CF-RAY: 7cd01186dbfee91e-DFW"
        [19]=>
        string(52) "alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400"
      }
      ["wrapper_type"]=>
      string(4) "http"
      ["stream_type"]=>
      string(14) "tcp_socket/ssl"
      ["mode"]=>
      string(2) "rb"
      ["unread_bytes"]=>
      int(203)
      ["seekable"]=>
      bool(false)
      ["uri"]=>
      string(262) "hiding my endpoints here"
    }
  }
}
```

Also when I first downloaded the plugin and tried to add a cmi5 course to it in Moodle I got an error. I fixed that by editing the courseid in the database. I'm wondering if that's causing the issue. 

```
Error writing to database

More information about this error

Debug info: Field 'courseid' doesn't have a default value
INSERT INTO mdl_cmi5launch (name,cmi5launchurl,cmi5activityid,overridedefaults,cmi5multipleregs,course,intro,introformat,timecreated) VALUES(?,?,?,?,?,?,?,?,?)
[array (
0 => 'nnnnnnn',
1 => 'http://localhost:63398/content',
2 => 'https://example.com/example-activity',
3 => '0',
4 => '1',
5 => '1',
6 => '',
7 => '1',
8 => 1685037514,
)]
Error code: dmlwriteexception×Dismiss this notification
Stack trace:
line 497 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 1455 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
line 1501 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 90 of /mod/cmi5launch/lib.php: call to mysqli_native_moodle_database->insert_record()
line 140 of /course/modlib.php: call to cmi5launch_add_instance()
line 175 of /course/modedit.php: call to add_moduleinfo()
```

**Comment by servosdesign** [comment]
Reinstalled the plugin from scratch and this is the error i'm getting 
image

**Pull request merged**
